services:
  - type: web
    name: cryptovault
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn aicryptovault.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DATABASE_URL
        fromDatabase:
          name: cryptovault-db
          property: connectionString

databases:
  - name: cryptovault-db
    databaseName: cryptovault
    user: cryptovault 